#!/bin/sh

# Insert annotations (from an annotation file) into a Java source file.
# For usage information, run: insert-annotations-to-source --help 
# See the annotation file utilities documentation for more information.

ROOT=`dirname $0`
ROOT=`cd $ROOT ; pwd`
ANNOTATION_FILE_UTILS=$ROOT/annotation-file-utilities.jar

# Contains Java 7 version of java.lang.annotation.ElementType.
JAVAC_HOME=`egrep '^javac.home' $ROOT/../../build.properties | awk -F= '{ print $2 }' | sed 's: *::g'`
JAVAC_JAR=$JAVAC_HOME/lib/javac.jar

# Augment, don't replace, CLASSPATH, so as to find user files.
# Can we can do without annotation-file-utilities.jar on bootclasspath?
java -ea "-Xbootclasspath/p:${JAVAC_JAR}" -cp ${ANNOTATION_FILE_UTILS}:${CLASSPATH} annotator.Main "$@"
